cmake_minimum_required(VERSION 3.22)

if (NOT DEFINED JUCE_SOURCE_DIR OR "${JUCE_SOURCE_DIR}" STREQUAL "")
    message(FATAL_ERROR "JUCE_SOURCE_DIR is required")
endif()
if (NOT DEFINED TEST_BINARY_DIR OR "${TEST_BINARY_DIR}" STREQUAL "")
    message(FATAL_ERROR "TEST_BINARY_DIR is required; fixtures must stay in the build directory")
endif()

get_filename_component(wasapi_patch_script
    "${CMAKE_CURRENT_LIST_DIR}/../cmake/PatchJuceWasapiSession.cmake" ABSOLUTE)
get_filename_component(wasapi_test_base "${TEST_BINARY_DIR}" ABSOLUTE)
string(RANDOM LENGTH 12 ALPHABET 0123456789abcdef wasapi_fixture_id)
set(wasapi_fixture_root "${wasapi_test_base}/wasapi-session-patch-${wasapi_fixture_id}")
set(wasapi_relative_source "modules/juce_audio_devices/native/juce_WASAPI_windows.cpp")
set(wasapi_original_sha256 "2083d9847c743d50deb16c519407b4f62ebfe609335397e24f1c224a93f4c3b3")
set(wasapi_patched_sha256  "e546d96a290c2cb7808561d4f30d6dacfe5cffd3ace318b6bbc629a2ffc24094")
set(wasapi_function_start "    bool initialiseStandardClient (")
set(wasapi_function_end   "    bool tryInitialisingWithBufferSize (")
set(wasapi_session_declaration "            GUID session;\n")
set(wasapi_original_argument   "                                          &session);")
set(wasapi_patched_argument    "                                          nullptr);")
set(wasapi_initialize_marker   "            auto hr = client->Initialize (")

function(normalize_and_hash contents normalized_output hash_output)
    string(REPLACE "\r\n" "\n" normalized "${contents}")
    string(SHA256 digest "${normalized}")
    set(${normalized_output} "${normalized}" PARENT_SCOPE)
    set(${hash_output} "${digest}" PARENT_SCOPE)
endfunction()

function(run_fixture_patch fixture should_succeed)
    execute_process(
        COMMAND "${CMAKE_COMMAND}" "-DJUCE_SOURCE_DIR=${fixture}" -P "${wasapi_patch_script}"
        RESULT_VARIABLE patch_result
        OUTPUT_VARIABLE patch_stdout
        ERROR_VARIABLE patch_stderr
    )
    if (should_succeed AND NOT patch_result EQUAL 0)
        message(FATAL_ERROR "Expected patch success for ${fixture}:\n${patch_stdout}\n${patch_stderr}")
    elseif (NOT should_succeed AND patch_result EQUAL 0)
        message(FATAL_ERROR "Patch incorrectly accepted unknown source: ${fixture}")
    elseif (NOT should_succeed AND NOT patch_stderr MATCHES "Unrecognised pinned JUCE WASAPI source")
        message(FATAL_ERROR "Failure did not come from the source-hash guard: ${patch_stderr}")
    endif()
    set(last_patch_stdout "${patch_stdout}" PARENT_SCOPE)
endfunction()

function(write_fixture name normalized_contents newline_style)
    set(fixture "${wasapi_fixture_root}/${name}")
    set(source "${fixture}/${wasapi_relative_source}")
    get_filename_component(source_directory "${source}" DIRECTORY)
    file(MAKE_DIRECTORY "${source_directory}")
    set(raw_contents "${normalized_contents}")
    if (newline_style STREQUAL "CRLF")
        string(REPLACE "\n" "\r\n" raw_contents "${raw_contents}")
    endif()
    file(WRITE "${source}" "${raw_contents}")
    set(current_fixture "${fixture}" PARENT_SCOPE)
    set(current_source "${source}" PARENT_SCOPE)
endfunction()

# Reconstruct the pristine fixture at test time by reversing the two reviewed
# edits in the fetched, already-patched dependency. No JUCE implementation
# snapshot is stored in this repository.
set(real_source "${JUCE_SOURCE_DIR}/${wasapi_relative_source}")
if (NOT EXISTS "${real_source}")
    message(FATAL_ERROR "Real JUCE WASAPI source is missing: ${real_source}")
endif()
file(READ "${real_source}" real_raw)
normalize_and_hash("${real_raw}" real_patched real_patched_hash)
if (NOT real_patched_hash STREQUAL wasapi_patched_sha256)
    message(FATAL_ERROR "Real JUCE WASAPI source is not the reviewed patched dependency")
endif()

string(FIND "${real_patched}" "${wasapi_function_start}" function_start_index)
string(FIND "${real_patched}" "${wasapi_function_end}" function_end_index)
if (function_start_index LESS 0 OR function_end_index LESS_EQUAL function_start_index)
    message(FATAL_ERROR "Unable to locate the reviewed standard-client function")
endif()
math(EXPR function_length "${function_end_index} - ${function_start_index}")
string(SUBSTRING "${real_patched}" ${function_start_index} ${function_length} patched_function)
string(SUBSTRING "${real_patched}" 0 ${function_start_index} source_prefix)
string(SUBSTRING "${real_patched}" ${function_end_index} -1 source_suffix)

string(REPLACE "${wasapi_patched_argument}" "${wasapi_original_argument}"
    original_function "${patched_function}")
string(REPLACE "${wasapi_initialize_marker}"
    "${wasapi_session_declaration}${wasapi_initialize_marker}"
    original_function "${original_function}")
set(real_original "${source_prefix}${original_function}${source_suffix}")
string(SHA256 real_original_hash "${real_original}")
if (NOT real_original_hash STREQUAL wasapi_original_sha256)
    message(FATAL_ERROR "Runtime reconstruction did not reproduce the reviewed pristine dependency")
endif()

foreach(newline_style IN ITEMS LF CRLF)
    string(TOLOWER "${newline_style}" newline_name)
    write_fixture("original-${newline_name}" "${real_original}" "${newline_style}")
    run_fixture_patch("${current_fixture}" TRUE)
    file(READ "${current_source}" actual_raw)
    normalize_and_hash("${actual_raw}" actual_normalized actual_hash)
    if (NOT actual_hash STREQUAL wasapi_patched_sha256)
        message(FATAL_ERROR "The ${newline_style} fixture did not reach the reviewed patched hash")
    endif()
    if (NOT last_patch_stdout MATCHES "Applied JUCE WASAPI default-session patch")
        message(FATAL_ERROR "Original ${newline_style} source was not reported as patched")
    endif()

    file(SHA256 "${current_source}" before_repeat)
    run_fixture_patch("${current_fixture}" TRUE)
    file(SHA256 "${current_source}" after_repeat)
    if (NOT before_repeat STREQUAL after_repeat
        OR NOT last_patch_stdout MATCHES "patch already applied")
        message(FATAL_ERROR "Repeat patch is not an already-applied no-op for ${newline_style}")
    endif()
endforeach()

set(unknown_source "${real_original}\n// synthetic unsupported edit\n")
write_fixture("unknown-edit" "${unknown_source}" "LF")
file(SHA256 "${current_source}" unknown_before)
run_fixture_patch("${current_fixture}" FALSE)
file(SHA256 "${current_source}" unknown_after)
if (NOT unknown_before STREQUAL unknown_after)
    message(FATAL_ERROR "Rejected unknown source was modified")
endif()

string(REPLACE "${wasapi_session_declaration}" "" partial_source "${real_original}")
write_fixture("partial-edit" "${partial_source}" "LF")
file(SHA256 "${current_source}" partial_before)
run_fixture_patch("${current_fixture}" FALSE)
file(SHA256 "${current_source}" partial_after)
if (NOT partial_before STREQUAL partial_after)
    message(FATAL_ERROR "Rejected partially patched source was modified")
endif()

file(REMOVE_RECURSE "${wasapi_fixture_root}")
message(STATUS "WASAPI session patch passed: pinned hashes, LF/CRLF, idempotence, and rejection safety")
message(STATUS "Fixture-only test; no audio device, session volume, or application state was changed")
