cmake_minimum_required(VERSION 3.22)

foreach(argument IN ITEMS INPUT OUTPUT OBJECT)
    if (NOT DEFINED ${argument} OR "${${argument}}" STREQUAL "")
        message(FATAL_ERROR "Missing dependency conversion argument: ${argument}")
    endif()
endforeach()

# CMake script errors (including file I/O) do not support catch/finally. Run the
# worker in a child so every failure invalidates its freshly compiled object.
if (NOT MSVC_DEPFILE_WORKER)
    execute_process(COMMAND "${CMAKE_COMMAND}"
        "-DINPUT=${INPUT}" "-DOUTPUT=${OUTPUT}" "-DOBJECT=${OBJECT}"
        -DMSVC_DEPFILE_WORKER=ON -P "${CMAKE_CURRENT_LIST_FILE}"
        RESULT_VARIABLE conversion_result)
    if (NOT conversion_result EQUAL 0)
        file(REMOVE "${OBJECT}" "${OUTPUT}" "${OUTPUT}.tmp")
        message(FATAL_ERROR "MSVC dependency conversion failed (${INPUT})")
    endif()
    return()
endif()

function(reject_evidence reason)
    # A failed conversion must not leave a fresh object that the next build
    # considers up-to-date without trustworthy dependencies.
    file(REMOVE "${OBJECT}" "${OUTPUT}")
    message(FATAL_ERROR "Invalid MSVC dependency JSON: ${reason} (${INPUT})")
endfunction()

function(escape_dependency result path)
    if (NOT IS_ABSOLUTE "${path}" OR NOT EXISTS "${path}" OR IS_DIRECTORY "${path}")
        reject_evidence("dependency is not an existing absolute file: ${path}")
    endif()
    if ("${path}" MATCHES "[\r\n]")
        reject_evidence("newline in dependency path")
    endif()
    string(REPLACE "\\" "/" escaped "${path}")
    string(REPLACE "$" "$$" escaped "${escaped}")
    string(REPLACE "#" "\\#" escaped "${escaped}")
    string(REPLACE ":" "\\:" escaped "${escaped}")
    string(REPLACE " " "\\ " escaped "${escaped}")
    set(${result} "${escaped}" PARENT_SCOPE)
endfunction()

if (NOT EXISTS "${INPUT}" OR IS_DIRECTORY "${INPUT}")
    reject_evidence("missing file")
endif()
file(READ "${INPUT}" json)
string(JSON version ERROR_VARIABLE error GET "${json}" Version)
if (error OR NOT version MATCHES "^1\\.[12]$")
    reject_evidence("missing or unsupported schema version")
endif()
string(JSON source ERROR_VARIABLE error GET "${json}" Data Source)
if (error)
    reject_evidence("missing source")
endif()
escape_dependency(source_dependency "${source}")
string(JSON includes_type ERROR_VARIABLE error TYPE "${json}" Data Includes)
if (error OR NOT includes_type STREQUAL "ARRAY")
    reject_evidence("Includes is not an array")
endif()
string(JSON count LENGTH "${json}" Data Includes)
string(REPLACE "\\" "/" object_target "${OBJECT}")
string(REPLACE "$" "$$" object_target "${object_target}")
string(REPLACE "#" "\\#" object_target "${object_target}")
string(REPLACE " " "\\ " object_target "${object_target}")
string(REPLACE ":" "\\:" object_target "${object_target}")
set(content "${object_target}: ${source_dependency}")
if (count GREATER 0)
    math(EXPR last "${count} - 1")
    foreach(index RANGE 0 ${last})
        string(JSON path_type TYPE "${json}" Data Includes ${index})
        if (NOT path_type STREQUAL "STRING")
            reject_evidence("include is not a string")
        endif()
        string(JSON path GET "${json}" Data Includes ${index})
        escape_dependency(dependency "${path}")
        string(APPEND content " \\\n  ${dependency}")
    endforeach()
endif()
# This project does not use C++ modules; refuse unsupported additional graphs.
foreach(field IN ITEMS ImportedModules ImportedHeaderUnits)
    string(JSON field_type ERROR_VARIABLE error TYPE "${json}" Data ${field})
    if (NOT error)
        string(JSON field_count ERROR_VARIABLE error LENGTH "${json}" Data ${field})
        if (error OR NOT field_count EQUAL 0)
            reject_evidence("unsupported nonempty ${field}")
        endif()
    endif()
endforeach()
file(WRITE "${OUTPUT}.tmp" "${content}\n")
file(RENAME "${OUTPUT}.tmp" "${OUTPUT}")
